name: ci_test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y build-essential xxd
    - name: test
      run: ./build-and-test.sh

